package com.xzy.forestSystem.hellocharts.formatter;

import com.xzy.forestSystem.hellocharts.model.AxisValue;

public interface AxisValueFormatter {
    int formatValueForAutoGeneratedAxis(char[] cArr, float f, int i);

    int formatValueForManualAxis(char[] cArr, AxisValue axisValue);
}
